# action.yml
name: 'Helm Push'
description: 'Pushes a local chart to a ChartMusem compatible repository. Supports token based auth and Chart.yaml version override.'
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  access-token:
    description: 'API Token with read/write permissions to the helm repository'
    required: false
    default: ''
  username:
    description: 'API Token with read/write permissions to the helm repository'
    required: false
    default: ''
  password:
    description: 'API Token with read/write permissions to the helm repository'
    required: false
    default: ''
  repository-url:
    description: 'Repository url'
    required: true
    default: ''
  chart-folder:
      description: 'Relative path to chart folder'
      required: false
      default: 'chart'
  version:
    description: 'Relative path to chart folder'
    required: false
    default: 'chart'
  force:
    description: 'Whether or not to override existing chart with same version'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://bsord/helm-push:latest'
  env:
    CHART_FOLDER: ${{ inputs.chart-folder }}
    FORCE: ${{ inputs.force }}
    CHARTMUSEUM_URL: ${{ inputs.repository-url }}
    CHARTMUSEUM_ACCESS_TOKEN: ${{ inputs.access-token }}
    CHARTMUSEUM_USERNAME: ${{ inputs.username }}
    CHARTMUSEUM_PASSWORD: ${{ inputs.password }}
    CHARTMUSEUM_VERSION: ${{ inputs.version }}
